info:
  project:
    name: @project.name@
    description: @project.description@
    version: @project.version@

errorHandler:
  messages:
    errorCreateEditorial: "Ha ocurrido un error al momento de crear editorial"
    errorCreateAutor: "Ha ocurrido un error al momento de crear autor"
    errorCreateCategoria: "Ha ocurrido un error al momento de crear categoria"

server:
  port: 8081
  servlet:
    context-path: /dummy-microservices-library-system

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:devdb
    driverClassName: org.h2.Driver
    username: dev
    password: dev
    hikari:
      maximum-pool-size: 10
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true