info:
  project:
    name: @project.name@
    description: @project.description@
    version: @project.version@

errorHandler:
  messages:
    errorCreatePrestamo: "Ha ocurrido un error al momento de crear prestamo"
    errorCreateAutor: "Ha ocurrido un error al momento de crear autor"
    errorCreateLibro: "Ha ocurrido un error al momento de crear libro"

server:
  port: 8081
  servlet:
    context-path: /dummy-microservices-library-system

# Configuración para el perfil de desarrollo/test (H2)
spring:
  profiles:
    active: local  # Perfil por defecto
  datasource:
    url: jdbc:h2:mem:devdb
    driverClassName: org.h2.Driver
    username: dev
    password: dev
    hikari:
      maximum-pool-size: 10
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none  # Usa create-drop para desarrollo si quieres que se eliminen las tablas al cerrar
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
      schema-locations: classpath:/db/h2/schema.sql
      data-locations: classpath:/db/h2/data.sql

---
# Configuración para el perfil de producción (Oracle)
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1  # Cambia la URL según tu configuración de Oracle
    driverClassName: oracle.jdbc.OracleDriver
    username: sys
    password: aolazo2437124371.
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate  # Para producción, no se recomienda "create-drop"
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
  sql:
    init:
      mode: always  # Ejecutar scripts SQL en Oracle también
      schema-locations: classpath:/db/oracle/schema.sql  # Especificar el esquema para Oracle
      data-locations: classpath:/db/oracle/data.sql  # Especificar los datos para Oracle
